# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webflux
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

#volumes:
#  postgres-data: